### ISSUE TITLE
`ecsmanage` not working

### ISSUE THREAD

**Issue by rajadain** [azavea/iow-boundary-tool#150]
## Overview

Running `manage ecsmanage resetdb` fails.

### Expected Behavior

It should succeed.

### Actual Behavior

```
kj manage ecsmanage resetdb
```
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/ecsmanage/management/commands/ecsmanage.py", line 44, in handle
    task_def_arn = self.get_task_def(config["TASK_DEFINITION_NAME"])
  File "/usr/local/lib/python3.8/site-packages/ecsmanage/management/commands/ecsmanage.py", line 136, in get_task_def
    return self.parse_response(task_def_response, "taskDefinitionArns", 0)
  File "/usr/local/lib/python3.8/site-packages/ecsmanage/management/commands/ecsmanage.py", line 113, in parse_response
    raise KeyError(msg)
```
```
KeyError: "Unexpected response from ECS API: {'taskDefinitionArns': [], 'ResponseMetadata': {'RequestId': 'd92224fa-40c1-458a-9ff8-63ba618c262e', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'd92224fa-40c1-458a-9ff8-63ba618c262e', 'content-type': 'application/x-amz-json-1.1', 'content-length': '25', 'date': 'Mon, 24 Oct 2022 15:58:07 GMT'}, 'RetryAttempts': 0}}"
```

**Comment by rajadain** [comment]
Running this returns an empty list:

```
aws --profile=iow-boundary-tool ecs list-task-definitions
```
```json
{
    "taskDefinitionArns": []
}
```

**Comment by rajadain** [comment]
This may be a side-effect of the last `develop` CI action failing: https://github.com/azavea/iow-boundary-tool/actions/runs/3313576625/jobs/5471742510

**Comment by rajadain** [comment]
That fixed it:

```
kj manage ecsmanage resetdb
```
```
Task started! View here:
https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/ecsStagingCluster/tasks/a25f5d84aeab43e191daf89d8401097b/details
```
